import {
  approveTracerLessonPlan,
  cancelTracerTask,
  createTracerAudioTask,
  createTracerVoicePreviewTask,
  createTracerCompositeTask,
  createTracerWorkflow,
  getTracerWorkflow,
  cancelTracerWorkflow,
  retryTracerWorkflow,
  createTracerPlanTask,
  createTracerRenderTask,
  getTracerAudioTimeline,
  getTracerDelivery,
  getTracerFinalMedia,
  getTracerLessonPlans,
  getTracerParseSnapshot,
  getTracerWorkspace,
  getTracerRenderedPages,
  getTracerTask,
  retryTracerTask,
  reviseTracerLessonPlan,
  setTracerRevisionLocked,
  uploadTracerPresentation,
} from "./real-tracer";

export const tracerApiAdapter = {
  uploadPresentation: uploadTracerPresentation,
  getTask: getTracerTask,
  retryTask: retryTracerTask,
  getParseSnapshot: getTracerParseSnapshot,
  getWorkspace: getTracerWorkspace,
  cancelTask: cancelTracerTask,
  createPlanTask: createTracerPlanTask,
  getLessonPlans: getTracerLessonPlans,
  reviseLessonPlan: reviseTracerLessonPlan,
  setRevisionLocked: setTracerRevisionLocked,
  approveLessonPlan: approveTracerLessonPlan,
  createAudioTask: createTracerAudioTask,
  createVoicePreviewTask: createTracerVoicePreviewTask,
  getAudioTimeline: getTracerAudioTimeline,
  createRenderTask: createTracerRenderTask,
  getRenderedPages: getTracerRenderedPages,
  createCompositeTask: createTracerCompositeTask,
  getFinalMedia: getTracerFinalMedia,
  getDelivery: getTracerDelivery,
  createWorkflow: createTracerWorkflow,
  getWorkflow: getTracerWorkflow,
  cancelWorkflow: cancelTracerWorkflow,
  retryWorkflow: retryTracerWorkflow,
} as const;

export function getEnabledTracerApiAdapter(value = process.env.NEXT_PUBLIC_PPT_DH_API_MODE) {
  return value === "stage-t" ? tracerApiAdapter : null;
}
