export type {
  Avatar,
  AvatarPosition,
  BackgroundStyle,
  CaptionStyle,
  Formula,
  FormulaStatus,
  Job,
  JobStage,
  JobStageStatus,
  JobStatus,
  JobType,
  ParsedSlide,
  Project,
  ProjectStatus,
  RenderResult,
  TeachingSettings,
  UploadStatus,
  UploadedFile,
  Voice,
} from "@ppt-digital-human/contracts";
